---
_init_helper:
  LOGFILE: PDBBRK_LOGFILE
  LEVEL: DEBUG
  HANDLER_NAME: PDB BREAK (DEBUG)

pytest_internalerror:
  1:
    args:
      - excinfo.type
      - excinfo.value

pytest_runtestloop:
  1:
    kwargs:
      wanted: attr.asdict(self.wanted)
      locs: >
        [attr.asdict(l) for l in locs]
  2:
    kwargs:
      "wanted.file": >
        "'' -> {}".format(self.wanted.file)
  3:
    args:
      - self.targets
    kwargs:
      target: attr.asdict(self.target)

runcall_until:
  pre_capfix:
    kwargs:
      kwargs: kwargs
  cap_top:
    kwargs:
      prevstdout: sys.stdout
  cap_bot:
    kwargs:
      stdout: type(sys.stdout)
      cap_method: self.capman._method
  post_capfix:
    args:
      - inst.botframe

pytest_pyfunc_call:
  1:
    args:
      - pyfuncitem.name
      - pyfuncitem.location
      - pyfuncitem.funcargs
      - self.target
    kwargs:
      "loc equals target": BreakLoc.from_pytest_item(pyfuncitem) == self.target
  2:
    args:
      - self.target
      - self.targets

find_breakable_line:
  1:
    args:
      - lineno
      - line
