
def test_fail_on_purpose():
    assert False
